### ISSUE TITLE
[BUG] the pagination of the tagList and postsWithTag seems not working properly

### ISSUE THREAD

**Issue by alpha-97** [GinoPane/oc-blogtaxonomy-plugin#61]
**Describe the bug**

The pagination of the tagList and postsWithTag seems not working properly

The first issue : the pagination link of the component PostwithTag is not working with the wrong URL.

The second issue : the tag link of the component tagList is incorrect when pagination is involved, when the current url come with the pagination parameter page, such page number will be appended to the tag link of the component tagList  which is incorrect.

Please help to look into it and let me know if further information is required, Thanks.

**To Reproduce**
1. Create a page with the component tagList and postswithTag
2. Implement pagination for the postwithTag page 
3. Check the URL of the links

Attached below the screenshots for your reference.

...

**Expected behavior**

**Screenshots**

![b1](https://user-images.githubusercontent.com/40558879/73861009-691c6c80-4877-11ea-8ea4-b204ab911e8e.jpg)
![b2](https://user-images.githubusercontent.com/40558879/73861016-6caff380-4877-11ea-8894-511198656981.jpg)
![b3](https://user-images.githubusercontent.com/40558879/73861022-6e79b700-4877-11ea-8baa-98cf5cdbca05.jpg)
![b4](https://user-images.githubusercontent.com/40558879/73861611-3b83f300-4878-11ea-9068-7597ad40a31f.jpg)
![b5](https://user-images.githubusercontent.com/40558879/73861617-3d4db680-4878-11ea-9de5-65df0d02cce6.jpg)

**Additional context**

**Comment by GinoPane** [comment]
@alpha-97 Hi! Thanks for your report.
Yep, it is a known issue with a default pagination. The default template is AJAX-based and it looks like your theme did not include required October scripts (AJAX front-end framework).

Anyway, I decided to replace the AJAX version with a simple pagination.

And that links issue was easy to miss, thanks for pointing out!

Both issues were addressed in a new release 2.0.3, please check it out.

**Comment by alpha-97** [comment]
Thanks for the quick fix.

After updating with the latest release, the second issue has been fixed while the first issue remains.

![b6](https://user-images.githubusercontent.com/40558879/74131019-6a0a2100-4c1e-11ea-8e7f-d8d5e9d0e72d.jpg)
![b7](https://user-images.githubusercontent.com/40558879/74131027-6eced500-4c1e-11ea-93aa-39bdcd21c843.jpg)
![b8](https://user-images.githubusercontent.com/40558879/74131032-72625c00-4c1e-11ea-9231-b6244b21b654.jpg)

**Comment by GinoPane** [comment]
@alpha-97 hm, that's strange. I'd suggest you to check if you really use an updated partial if you can. Also, the default partial is not intended to be used in production, so you'll have to update it anyway.

Maybe the old one is cached or something.
