### ISSUE TITLE
I'm getting error on clean install with latest octobercms version [BUG]

### ISSUE THREAD

**Issue by haralake** [GinoPane/oc-blogtaxonomy-plugin#97]
**Describe the bug**
On a clean install on octobercms 2.0.9 and latest blogtaxonomy plugin i get error:
`
SQLSTATE[42000]: Syntax error or access violation: 1055 'test_local.ginopane_blogtaxonomy_tags.name' isn't in GROUP BY (SQL: select `ginopane_blogtaxonomy_tags`.*, (select count(*) from `rainlab_blog_posts` inner join `ginopane_blogtaxonomy_taggables` on `rainlab_blog_posts`.`id` = `ginopane_blogtaxonomy_taggables`.`ginopane_blogtaxonomy_taggable_id` where `ginopane_blogtaxonomy_tags`.`id` = `ginopane_blogtaxonomy_taggables`.`tag_id` and `ginopane_blogtaxonomy_taggables`.`ginopane_blogtaxonomy_taggable_type` = RainLab\Blog\Models\Post and `published` is not null and `published` = 1 and `published_at` is not null and `published_at` < 2021-04-22 12:52:22) as `posts_count`, (select count(*) from `ginopane_blogtaxonomy_series` inner join `ginopane_blogtaxonomy_taggables` on `ginopane_blogtaxonomy_series`.`id` = `ginopane_blogtaxonomy_taggables`.`ginopane_blogtaxonomy_taggable_id` where `ginopane_blogtaxonomy_tags`.`id` = `ginopane_blogtaxonomy_taggables`.`tag_id` and `ginopane_blogtaxonomy_taggables`.`ginopane_blogtaxonomy_taggable_type` = GinoPane\BlogTaxonomy\Models\Series) as `series_count` from `ginopane_blogtaxonomy_tags` group by `id` having `posts_count` > 0 or `series_count` > 0 order by `name` asc limit 20)
`

Installed latest blogtaxonomy plugin version.
I also run db migration.

This error comes from component taglist. Without component everything is working fine.

**Comment by GinoPane** [comment]
@haralake Hi! Could you please also share the component settings you use?

**Comment by haralake** [comment]
I get this error also on default component settings. I just insert component on footer partial on demo theme and get this error.

**Comment by GinoPane** [comment]
@haralake please try a new 3.0.3 version

**Comment by haralake** [comment]
Installed latest version 3.0.3, but i'm still getting the same error. Both on my local and my live server. Any thoughts will be valuable.
![Exception](https://user-images.githubusercontent.com/18325407/115959007-ad466c00-a512-11eb-8783-d32846e82d0f.png)

**Comment by GinoPane** [comment]
@haralake please check that you definitely installed an update. If possible, check directly in the code:

![image](https://user-images.githubusercontent.com/3897579/115985409-6b6e0200-a5b4-11eb-8d89-6cfde4080605.png)

Because from what I see, you are still using old code.

The same query on 3.0.3 looks like this:

![image](https://user-images.githubusercontent.com/3897579/115985483-bb4cc900-a5b4-11eb-85b6-32b7c78ca5d3.png)

So it is different from what you have.

Please let me know what you find.

**Comment by haralake** [comment]
I checked the code and is updated. But i get error:
![Exception](https://user-images.githubusercontent.com/18325407/116117324-c55ded00-a6c4-11eb-8dd4-c823b7a7282a.png)

**Comment by GinoPane** [comment]
@haralake you checked the code and what did you see on the lines I mentioned?

I went to October website and checked the updates status for the plugin, it showed that the latest build failed for whatever reason:
![image](https://user-images.githubusercontent.com/3897579/116199065-612c3f00-a73f-11eb-859e-16d4e1785af8.png)

So you clearly haven't updated and probably haven't checked the code either. Please be honest in your responses, I won't be able to help otherwise.

I pushed another update to fix the October's marketplace issue. It will be 3.0.4

**Comment by haralake** [comment]
Do not rush to conclusions please. I tried to do the upgrade via composer but I saw that the last one you had up was 3.0.2, so I downloaded the latest version 3.0.3 from git and transferred it to the server. Then I ran php artisan october: migrate and was informed about the upgrade to version 3.0.3. Your code is there but the error persists. 
Why do you think I would like to lie to you, since that would not help solve my problem.
![Screenshot_3](https://user-images.githubusercontent.com/18325407/116223554-4fa36100-a758-11eb-9f93-4d22b7735f39.png)
![Screenshot_5](https://user-images.githubusercontent.com/18325407/116223569-54681500-a758-11eb-8b9e-031905214e9b.png)
![Screenshot_4](https://user-images.githubusercontent.com/18325407/116223578-5631d880-a758-11eb-9840-bbd59684533a.png)

**Comment by GinoPane** [comment]
Cool! Thanks for clarifications. I didn't mean to offend you in any way.

As I see you are familiar with development, so could you please debug and investigate a little? I wonder which value `$sortField` has and if the code flow goes into the `if` clause. Because as long as you sort by "name" (it is seen from the query), the `$sortField` must be "name" and `$query->groupBy('id', $sortField)` must be called. 

I wonder what may go wrong here and why you still have an issue. Because the issue is not reproducible for me (I showed the query from my setup several messages above).

**Comment by ketihar** [comment]
I can confirm that bug. I also get the same error after update to Octobercms v.2. I have installed latest octobercms version v2.0.11 and latest plugin version v.3.0.4.

**Comment by arachnadigital** [comment]
Also confirming the bug on octobercms version v2.0.11

**Comment by GinoPane** [comment]
Hm, to be honest I haven't tried v2 yet.
How did you install it? 😃

**Comment by GinoPane** [comment]
Ok, I see, there's no free option, you have to pay even just to try or develop for it. F#ck this, it is frustrating.

**Comment by daftspunk** [comment]
@GinoPane email us?

**Comment by daftspunk** [comment]
Tested this on October v2.0.11 using SQLite and MySQL, no error. Plugin is v3.0.4

```
select `ginopane_blogtaxonomy_tags`.*, (select count(*) from `rainlab_blog_posts` inner join `ginopane_blogtaxonomy_taggables` on `rainlab_blog_posts`.`id` = `ginopane_blogtaxonomy_taggables`.`ginopane_blogtaxonomy_taggable_id` where `ginopane_blogtaxonomy_tags`.`id` = `ginopane_blogtaxonomy_taggables`.`tag_id` and `ginopane_blogtaxonomy_taggables`.`ginopane_blogtaxonomy_taggable_type` = ? and `published` is not null and `published` = ? and `published_at` is not null and `published_at` < ?) as `posts_count`, (select count(*) from `ginopane_blogtaxonomy_series` inner join `ginopane_blogtaxonomy_taggables` on `ginopane_blogtaxonomy_series`.`id` = `ginopane_blogtaxonomy_taggables`.`ginopane_blogtaxonomy_taggable_id` where `ginopane_blogtaxonomy_tags`.`id` = `ginopane_blogtaxonomy_taggables`.`tag_id` and `ginopane_blogtaxonomy_taggables`.`ginopane_blogtaxonomy_taggable_type` = ?) as `series_count` from `ginopane_blogtaxonomy_tags` group by `id`, `name` having `posts_count` > ? or `series_count` > ? order by `name` asc  
```

The query includes the `name` in group by. Everything looks fine over here

**Comment by GinoPane** [comment]
@daftspunk thanks for looking into that! Hm, weird. 
I'll probably have to test and investigate on my own or wait for PR from someone who can reproduce the issue.

@arachnadigital @haralake @ketihar what DB servers (with versions) do you use guys? I wonder if it works for SQLite (which I use also) but fails for some other servers.

**Comment by ketihar** [comment]
I use mysqld  Ver 10.5.6-MariaDB-1:10.5.6

**Comment by arachnadigital** [comment]
Hi @GinoPane, I'm on 10.4.17-MariaDB

**Comment by daftspunk** [comment]
The issue does not appear related to the DB engine, rather, it is the query the is generated. Even though you have the latest code, it does not appear to be getting applied to the query string. We should expect to see

```
group by `id`, `name`
```

We should NOT expect to see `name` missing

```
group by `id`
```

This could be caused by any number of reasons and the information provided so far is conflicting. Only thing I could suggest is to reinstall the plugin, otherwise, it is difficult to troubleshoot something that we can't replicate

**Comment by GinoPane** [comment]
@daftspunk I'd expect some group by behavior differences based on DB engine, but I haven't looked there in detail.

Of course it would be nice if someone who can reproduce the issue would provide more details and do a little investigation.

**Comment by daftspunk** [comment]
@GinoPane If the logic targets a SQLite complaint specifically it could be worthwhile to only apply it if

```
if (\Db::getDriverName() === 'sqlite') {
    // ...
}
```

**Comment by GinoPane** [comment]
Yep, I thought about that, it would be a backup plan.
Right now it is interesting to find the reason

**Comment by GinoPane** [comment]
Installed the latest October with the latest plugin, used the TagList with default settings and had no issues:

**Comment by GinoPane** [comment]
Guys, please check if you still have the issue on the 3.0.5 version.

This was definitely something related to MySQL settings according to the group by behaviour. For me it failed on a "slug" field though I didn't have it in the query at all (due to required "full-group-by")

**Comment by ketihar** [comment]
Latest version fixed it. Thank you.
